In [1]:
import pandas as pd
import numpy as np

In [2]:
Dataset = pd.read_csv("heart disease.csv")

In [3]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.2 KB


In [5]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale

In [7]:
data_nor = scale(Dataset)

In [8]:
data_nor

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -0.71442887,
        -2.14887271,  0.91452919],
       [-1.91531289,  0.68100522,  1.00257707, ..., -0.71442887,
        -0.51292188,  0.91452919],
       [-1.47415758, -1.46841752,  0.03203122, ..., -0.71442887,
        -0.51292188,  0.91452919],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ...,  1.24459328,
         1.12302895, -1.09345881],
       [ 0.29046364,  0.68100522, -0.93851463, ...,  0.26508221,
         1.12302895, -1.09345881],
       [ 0.29046364, -1.46841752,  0.03203122, ...,  0.26508221,
        -0.51292188, -1.09345881]])

In [12]:
pca = PCA(n_components = 13)
pca_values = pca.fit_transform(data_nor)

In [18]:
pca_values
pca_data = pd.DataFrame(pca_values)
pca_data

0         1         2         3         4         5         6  \
0   -0.051739  2.624022  0.990054  3.479328  0.362773  1.695836 -0.135706   
1   -0.817441 -0.730375 -0.235928  2.767545  2.258404 -0.808414 -0.104445   
2   -2.057599 -0.039098 -0.519839  0.081198  0.860416  0.752783 -0.133915   
3   -1.903043 -0.596701  0.076204 -0.082624 -0.235141 -0.500292 -0.136878   
4   -0.768371  0.412545 -2.187455 -1.988510  0.017448 -0.074219  1.433544   
..        ...       ...       ...       ...       ...       ...       ...   
298  1.485287 -0.423483 -1.683247 -0.490555 -0.187162 -0.525461  1.539102   
299 -0.140325 -1.215922  0.138325  0.977923  0.884803 -1.240199 -0.710762   
300  2.681772  0.593019  1.791015  1.300262 -1.331351 -1.201660  0.558171   
301  2.170858 -2.166992 -0.081516  0.890244 -1.177444 -0.346770  0.462081   
302 -0.365760  0.787916 -0.395860 -0.421878  0.203408  0.561283 -0.811041   

            7         8         9        10        11        12  
0    0.739775 -0.536037  0.967674 -0.530379 -0.469128  0.412631  
1    1.503700  1.290094  1.111370 -0.342366 -0.469777  0.238654  
2   -0.095343  1.279945 -1.189688  0.368036 -0.157562 -1.103773  
3   -0.171773 -0.164652  0.702923 -0.609533 -1.152772 -0.147857  
4    0.615901 -0.219965  0.871529  0.525989 -0.969506 -0.076504  
..        ...       ...       ...       ...       ...       ...  
298 -0.722948 -0.516262 -1.078705  0.249491  0.804541  0.738609  
299  1.047574 -1.478738  0.440635  0.142995  1.634516 -0.087107  
300  0.710281  0.217872 -0.907961 -1.409135 -1.005306 -0.744443  
301 -1.163514 -0.461829 -0.973929  0.352957  0.111530  0.352377  
302  0.113782  1.045750 -0.981688 -0.163579  0.197289  1.269430  

[303 rows x 13 columns]

In [14]:
var = pca.explained_variance_ratio_
var

array([0.23581966, 0.11229748, 0.08800207, 0.08618849, 0.07300207,
       0.06929774, 0.06165962, 0.05543521, 0.05208534, 0.04448005,
       0.03817159, 0.03071669, 0.02656258])

In [16]:
#cumulative var

var1 = np.cumsum(np.round(var, decimals =2)*100)
var1

array([24., 35., 44., 53., 60., 67., 73., 79., 84., 88., 92., 95., 98.])

In [19]:
final = pca_data.iloc[:,[0,1,2,3,4,5]]

In [20]:
final

0         1         2         3         4         5
0   -0.051739  2.624022  0.990054  3.479328  0.362773  1.695836
1   -0.817441 -0.730375 -0.235928  2.767545  2.258404 -0.808414
2   -2.057599 -0.039098 -0.519839  0.081198  0.860416  0.752783
3   -1.903043 -0.596701  0.076204 -0.082624 -0.235141 -0.500292
4   -0.768371  0.412545 -2.187455 -1.988510  0.017448 -0.074219
..        ...       ...       ...       ...       ...       ...
298  1.485287 -0.423483 -1.683247 -0.490555 -0.187162 -0.525461
299 -0.140325 -1.215922  0.138325  0.977923  0.884803 -1.240199
300  2.681772  0.593019  1.791015  1.300262 -1.331351 -1.201660
301  2.170858 -2.166992 -0.081516  0.890244 -1.177444 -0.346770
302 -0.365760  0.787916 -0.395860 -0.421878  0.203408  0.561283

[303 rows x 6 columns]