In [21]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

In [22]:
Dataset = pd.read_csv("wine.csv")
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Type             178 non-null    int64  
 1   Alcohol          178 non-null    float64
 2   Malic            178 non-null    float64
 3   Ash              178 non-null    float64
 4   Alcalinity       178 non-null    float64
 5   Magnesium        178 non-null    int64  
 6   Phenols          178 non-null    float64
 7   Flavanoids       178 non-null    float64
 8   Nonflavanoids    178 non-null    float64
 9   Proanthocyanins  178 non-null    float64
 10  Color            178 non-null    float64
 11  Hue              178 non-null    float64
 12  Dilution         178 non-null    float64
 13  Proline          178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.5 KB


In [23]:
data_nor = scale(Dataset)

In [24]:
data_nor

array([[-1.21394365,  1.51861254, -0.5622498 , ...,  0.36217728,
         1.84791957,  1.01300893],
       [-1.21394365,  0.24628963, -0.49941338, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [-1.21394365,  0.19687903,  0.02123125, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 1.37386437,  0.33275817,  1.74474449, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 1.37386437,  0.20923168,  0.22769377, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.37386437,  1.39508604,  1.58316512, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [28]:
pca = PCA(n_components = 13)
pca_values = pca.fit_transform(data_nor)
pca_data = pd.DataFrame(pca_values)
pca_data

0         1         2         3         4         5         6  \
0   -3.522934 -1.453098 -0.164795 -0.013273  0.737345 -0.300716  0.573876   
1   -2.528858  0.330019 -2.026707 -0.417144 -0.283214 -0.884309 -0.029716   
2   -2.785029 -1.036936  0.983238  0.664232 -0.387565  0.468842  0.488305   
3   -3.922588 -2.768210 -0.174968  0.565088 -0.324360  0.262616 -0.398364   
4   -1.407511 -0.867773  2.025829 -0.440906  0.227949 -0.593762  0.447876   
..        ...       ...       ...       ...       ...       ...       ...   
173  3.627996 -2.206617 -0.343668  0.751705 -1.004109 -1.143155  0.843455   
174  2.942729 -1.752263  0.207480  0.399381  0.154223 -0.062465  0.139947   
175  3.027272 -2.756040 -0.940803  0.607758  1.128136  0.005290  0.733026   
176  2.755222 -2.293784 -0.550474 -0.391570  1.067083  1.012562  0.755423   
177  3.496336 -2.760608  1.013151  0.349630 -1.005136  0.377223  0.015307   

            7         8         9        10        11        12  
0    0.055637 -0.458765  1.065570 -0.420494  0.552928 -0.302978  
1    1.010372  0.218806 -0.020182 -0.130020  0.394971 -0.146645  
2   -0.268957  1.222769 -0.106249 -0.279074  0.001898  0.021278  
3    0.618844 -0.114658  0.107671  0.773866 -0.230929 -0.501277  
4    0.434937 -0.261548  0.112434 -0.537931 -0.226686  0.274109  
..        ...       ...       ...       ...       ...       ...  
173 -0.206626 -0.125419 -0.392619  0.136783  0.174807 -0.198803  
174 -0.565588  0.055341 -0.236267  0.254286 -0.277519 -0.185064  
175  0.052545 -0.027881 -0.212749  0.502640  0.693336  0.167036  
176  0.426512  0.048784  0.479793  0.313786  0.344120 -0.109515  
177 -0.325002 -0.719983  0.079908 -0.238282 -0.189866 -0.164090  

[178 rows x 13 columns]

In [29]:
# variance

var = pca.explained_variance_ratio_
var

array([0.39542486, 0.17836259, 0.10329102, 0.06627984, 0.06267875,
       0.0480556 , 0.03955707, 0.02500244, 0.02103871, 0.01873615,
       0.01613203, 0.01205691, 0.00925458])

In [31]:
#cumulative variance
var1 = np.cumsum(np.round(var, decimals=4)*100)
var1

array([39.54, 57.38, 67.71, 74.34, 80.61, 85.42, 89.38, 91.88, 93.98,
       95.85, 97.46, 98.67, 99.6 ])

In [34]:
final = pca_data.iloc[:,[0,1,2]]
final

0         1         2
0   -3.522934 -1.453098 -0.164795
1   -2.528858  0.330019 -2.026707
2   -2.785029 -1.036936  0.983238
3   -3.922588 -2.768210 -0.174968
4   -1.407511 -0.867773  2.025829
..        ...       ...       ...
173  3.627996 -2.206617 -0.343668
174  2.942729 -1.752263  0.207480
175  3.027272 -2.756040 -0.940803
176  2.755222 -2.293784 -0.550474
177  3.496336 -2.760608  1.013151

[178 rows x 3 columns]